/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 phantoms.glb --transform
*/
"use client";

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from 'gsap'

export default function Robot(props) {
  const { nodes, materials } = useGLTF(
    "./models/robots/phantoms-transformed.glb"
  );
  const robot = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  });

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(robot.current.rotation, {y: -1}, 3)
    .to(robot.current.position, {x: 1}, 3)

    .to(robot.current.rotation, {y: 1}, 9)   
    .to(robot.current.position, {x: -1}, 9)

    .to(robot.current.rotation, {y: 0}, 20)
    .to(robot.current.rotation, {x: 1}, 20)
    .to(robot.current.position, {x: 0}, 20)

    .to(robot.current.rotation, {y: 0}, 26)
    .to(robot.current.rotation, {x: -1}, 26)    
    .to(robot.current.position, {x: 0}, 26)

    // .to(robot.current.rotation, {y: 0}, 28)   
    // .to(robot.current.rotation, {x: 0}, 28) 
    // .to(robot.current.position, {x: 0}, 28)    

    // .to(robot.current.rotation, {y: 0}, 27)   
    // .to(robot.current.rotation, {x: 0}, 27) 
    // .to(robot.current.position, {x: 0}, 27)   

  },[]);

  return (
    <group {...props} dispose={null} ref={robot}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Metal}
        position={[-0.214, 0.163, 0.365]}
        rotation={[0, -0.152, 0]}
        scale={0.146}
        castShadow
      >
        <meshPhysicalMaterial
          color="#aaa"
          roughness={0.2}
          metalness={1}
          reflectivity={0.5}
          iridescence={0.3}
          iridescenceIOR={1}
          iridescenceThicknessRange={[100, 1000]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/robots/phantoms-transformed.glb");
